# Generated by Django 4.0.2 on 2022-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='suggestion2',
            field=models.CharField(default='test', max_length=240),
        ),
    ]
