# Generated by Django 4.0.2 on 2022-02-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_suggestionmodel_suggestion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionmodel',
            name='suggestion2',
        ),
    ]
